### ISSUE TITLE
ava.lang.Exception: Toast callstack! 

### ISSUE THREAD

**Issue by JimmyZou92** [afkT/DevUtils#24]
设备是雷电模拟器4.0.68
安卓版本是25
使用 ToastUtils.showShort("跳过广告") 的时候报错

 java.lang.Exception: Toast callstack! strTip=跳过广告
     at android.widget.Toast.show(Toast.java:130)
     at dev.utils.app.toast.ToastUtils.lambda$priShowToastText$0(ToastUtils.java:504)
     at dev.utils.app.toast.ToastUtils$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6161)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by afkT** [comment]
近几天暂时没时间，等我空闲看下，如确认了会在下个版本修复。

**Comment by afkT** [comment]
hi，还在吗，你用的是 DevApp 什么版本的呢，我试过最新的，没有复现过，网上搜索出现的情况也很少，暂时不确定是什么原因导致、如何复现的。

如果还有出现且影响使用了，你再提 issue。
